server:
  port: 8085
spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: http://localhost:7172
          predicates:
            - Path=/users/**
        - id: PRODUCT-SERVICE
          uri: http://localhost:7172
          predicates:
            - Path=/product/**
        - id: CART-SERVICE
          uri: http://localhost:7171
          predicates:
            - Path=/cart/**